name: CI
on:
  push:
    branches:
      - main
      - master
      - dev
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
      - dev
      - release-*

jobs:
  CI:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up nodejs version ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean Cache
      run: npm cache clean --force
    - name: Install package
      run: npm install
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm run test
    - name: CodeClimate Scan
      uses: paambaati/codeclimate-action@v6.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TOKEN }}
      with:
        coverageLocations: |
          ${{github.workspace}}/coverage/*.info:lcov  
          ${{github.workspace}}/coverage/clover.xml:clover  
        debug: true
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with: 
        args: >
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=santoshshinde2012
          -Dsonar.projectKey=santoshshinde2012_node-boilerplate
          -Dsonar.projectName=node-boilerplate
          -Dsonar.projectVersion=1.0
          -Dsonar.language=ts
          -Dsonar.sources=.
          -Dsonar.tests=./tests
          -Dsonar.test.inclusions=**/tests/**/*.ts
          -Dsonar.coverage.exclusions=**/tests/**/*.ts,/**/src/server.ts,node_modules/*,coverage/lcov-report/*,jest.config.ts
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info 
          -Dsonar.testExecutionReportPaths=coverage/sonar-report.xml
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.verbose=false
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}